# https://docs.travis-ci.com/user/languages/dart/
language: dart
dart:
  - stable

before_script:
  # https://flutter.dev/docs/get-started/web
  - git clone https://github.com/flutter/flutter.git -b beta
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter upgrade
  - flutter config --enable-web
  - flutter doctor

script:
  - cd client
  - flutter build web
  - cd ..
  - cp -R ./client/build/web/* ./public
  - echo "clean up before"
  - rm -rf ./client
  - rm -rf ./.vscode
  - ls -la ./public



# Deploy configuration
# Use the Flutter console to configure your web app. 
# https://docs.travis-ci.com/user/deployment/firebase/
deploy:
  provider: firebase
  token:
    secure: "CugRCg8BvJmQ3q5n/ooQi4agWn94dBHFmEZr7mlzSnyxUK5uFY6WcDNDG4RMz+LJ3dmK9TQflv1QeSYx0/CZXWhuBVQu3Rv9W7GFHE19Ek9pxUPraoaH1Pi5YB/w6ufgBAHREgVR74iknqp40Zpb13QV+uD1YIj4bncrBkL1fhB2AFTEBRZXW7KBOPhhVnhflErVhB9xGQZ9bt6+gHvepOVW56WSi6ZcPncStx1vfSC8ktJp8EUQvCdEdEfodZ8IEW+ICILZrqkr3e44ezR2Zjb+B9c2akDPZL3GAUGXZJfaxDQ96X9PgIQ1Cm5W/a9rcwJpXiKQeP2LNJuXASMwL9g0DAqsDdL6Cgh79CbyE42N7VRTMYplSrO2FWMPaBC5K/BICzyH9VGMlqsg7Pes+/11JtJRj1PnCE4XzJHMJ/3mbIx/iUvAspvew+ck5RYczlxe7A4RQqlzNjgbVnFnXrikeVCsUgYESiWNmCNlEet4prkfhWEOTrIfyuWVeh/Q7k2EgcE//Kz0OWdcnPWnj2DJZntjl9F0vmFL5AEAl1scEaeVLQNpaJXa7vrsNZV0Xxe1Og53PCRdXOo8o+j4Et6OU4bfh60iqLNQ3inmW8CJ/WjwBimbF5FQF9JyPo/DQnWaeTTIW+z3Z5DKgzrLHxUN2mxiOyEQI/DOVkqzGYk="
  project: "donnelson-sandbox"


    
# Run Travis CLI in this repo
# gem install travis

# Delete Travis Cache
# travis cache --com
# travis cache --com --delete

# Firebase tools
# https://github.com/firebase/firebase-tools#installation - Use this to get your token($FIREBASE_TOKEN)

# Encrypt Secure Variables
# gem install travis
# travis login --github-token replace_with_github_personal_token
# cd to/this/repo
# travis encrypt "$FIREBASE_TOKEN"  

# Deploy
# firebase deploy --token "$FIREBASE_TOKEN"